-- Names for this trainer's 51-item pool only. IDs are verified against the
-- installed game's CollectibleType enum; display names against local EID's
-- Chinese/English item-name references. No runtime dependency on EID.
return {
    [1] = { zh = "悲伤洋葱", en = "The Sad Onion" },
    [2] = { zh = "内眼", en = "The Inner Eye" },
    [3] = { zh = "弯勺魔术", en = "Spoon Bender" },
    [4] = { zh = "柯吉猫的头", en = "Cricket's Head" },
    [5] = { zh = "我的镜像", en = "My Reflection" },
    [6] = { zh = "小号", en = "Number One" },
    [7] = { zh = "殉道者之血", en = "Blood of the Martyr" },
    [32] = { zh = "铁丝衣架", en = "Wire Coat Hanger" },
    [46] = { zh = "幸运脚", en = "Lucky Foot" },
    [48] = { zh = "丘比特之箭", en = "Cupid's Arrow" },
    [51] = { zh = "五芒星", en = "Pentagram" },
    [52] = { zh = "胎儿博士", en = "Dr. Fetus" },
    [53] = { zh = "万磁王", en = "Magneto" },
    [54] = { zh = "藏宝图", en = "Treasure Map" },
    [68] = { zh = "科技", en = "Technology" },
    [69] = { zh = "巧克力牛奶", en = "Chocolate Milk" },
    [89] = { zh = "蜘蛛之咬", en = "Spider Bite" },
    [104] = { zh = "寄生虫", en = "The Parasite" },
    [132] = { zh = "煤块", en = "A Lump of Coal" },
    [149] = { zh = "吐根酊", en = "Ipecac" },
    [152] = { zh = "科技II", en = "Technology 2" },
    [153] = { zh = "变异蜘蛛", en = "Mutant Spider" },
    [169] = { zh = "巨人独眼", en = "Polyphemus" },
    [182] = { zh = "圣心", en = "Sacred Heart" },
    [183] = { zh = "牙签", en = "Tooth Picks" },
    [213] = { zh = "丢失的隐形眼镜", en = "Lost Contact" },
    [231] = { zh = "焦油球", en = "Ball of Tar" },
    [237] = { zh = "死神之触", en = "Death's Touch" },
    [243] = { zh = "三位一体盾", en = "Trinity Shield" },
    [245] = { zh = "完美视力", en = "20/20" },
    [255] = { zh = "螺丝", en = "Screw" },
    [259] = { zh = "暗物质", en = "Dark Matter" },
    [261] = { zh = "眼球突出", en = "Proptosis" },
    [305] = { zh = "天蝎座", en = "Scorpio" },
    [317] = { zh = "神秘液体", en = "Mysterious Liquid" },
    [331] = { zh = "神性", en = "Godhead" },
    [369] = { zh = "连续统", en = "Continuum" },
    [373] = { zh = "死亡之眼", en = "Dead Eye" },
    [374] = { zh = "圣光", en = "Holy Light" },
    [379] = { zh = "双瞳", en = "Pupula Duplex" },
    [398] = { zh = "神体蘑菇", en = "God's Flesh" },
    [401] = { zh = "爆炸物", en = "Explosivo" },
    [462] = { zh = "彼列之眼", en = "Eye of Belial" },
    [463] = { zh = "硫酸", en = "Sulfuric Acid" },
    [494] = { zh = "雅各布天梯", en = "Jacob's Ladder" },
    [495] = { zh = "断魂椒", en = "Ghost Pepper" },
    [524] = { zh = "科技零", en = "Technology Zero" },
    [531] = { zh = "泪血症", en = "Haemolacria" },
    [533] = { zh = "三圣颂", en = "Trisagion" },
    [596] = { zh = "天王星", en = "Uranus" },
    [597] = { zh = "海王星", en = "Neptunus" },
}
